### PR TITLE
Fixed the functionality for deleting users.

### LINKED ISSUE #49: Users can't be deleted
It crashes when you try to delete one.

### PR DESCRIPTION
**Pull request by CarlEnglund**
The destroy function was commented away. Works now.
fixes #49

### CODE REVIEW

File: app/controllers/users_controller.rb [hunk 1]
```diff
@@ -26,14 +26,14 @@ def show
   # def update
   # end
 
-  # def destroy
-  #   @user = User.find(params[:id])
-  #   @user.destroy
+  def destroy
+     @user = User.find(params[:id])
```
Comment (klaseskilson) [inline app/controllers/users_controller.rb]: This is already done by the `set_user` method.

File: app/controllers/users_controller.rb [hunk 2]
```diff
@@ -26,14 +26,14 @@ def show
...
+     @user.destroy
```
Comment (klaseskilson) [inline app/controllers/users_controller.rb]: No need to do this twice, right? The if statement below handles it.

File: app/controllers/users_controller.rb [hunk 3]
```diff
@@ -26,14 +26,14 @@ def show
...
 
-  #   if @user.destroy
-  #       redirect_to root_url, notice: "User deleted."
-  #   end
-  # end
+     if @user.destroy
+         redirect_to users_path, notice: "Användare borttagen."
+     end
```
Comment (klaseskilson) [inline app/controllers/users_controller.rb]: What happens if this fails? I suggest we add the following in an else statement.

```ruby
redirect_to users_path, notice: "Användare kunde inte tas bort."
```

**Comment by klaseskilson** [comment]
Nice work! Left a couple of comments that I think should be taken care of before merge. :beer:

**Comment by klaseskilson** [comment]
Committed some changes in 72f3e37. What do you think, @CarlEnglund?
